# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-android/ for more details
#
version: 2

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: ~/SeriesGuide

    docker:
      - image: circleci/android:api-29

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Init
          command: |
            chmod +x gradlew
            ./gradlew -version
      # Reduce memory usage to avoid UnmarshalException of Kotlin daemon (re-uses Gradle daemon heap size).
      - run:
          name: Assemble
          command: ./gradlew assembleDebug -Dorg.gradle.jvmargs="-Xmx1024M"

      - run:
          name: Run Tests
          command: ./gradlew :app:test -Dorg.gradle.jvmargs="-Xmx1024M"
      - store_test_results:
          path: app/build/test-results

      - run:
          # To speed up lint check only run for release variant and only on app module
          # Note: the app module has lintOptions.checkDependencies true, so submodules will be checked
          # Source: https://groups.google.com/forum/#!topic/lint-dev/RGTvK_uHQGQ
          name: Run Lint
          command: ./gradlew :app:lintPureRelease :app:lintAmazonRelease -Dorg.gradle.jvmargs="-Xmx1024M"
      - store_artifacts:
          path: app/build/reports/lint-results-pureRelease.html
          destination: lint-results-goog.html
      - store_artifacts:
          path: app/build/reports/lint-results-amazonRelease.html
          destination: lint-results-amaz.html

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
